### ISSUE TITLE
The board should be centered

### ISSUE THREAD

**Issue by ludamad** [ludamad/boarders#1]
The board should be directly in the middle, and the player info blocks to the right of it.  One player info block should be top aligned while the other one bottom aligned. The buttons should be below the board.

**Comment by blabtonic** [comment]
been looking into the center alignment as well as the responsiveness of the board as well

**Comment by ludamad** [comment]
Alright, feel free to open anything like that as an issue so there's places to discuss design.

**Comment by putterson** [comment]
Are we allowed to use flexbox?
http://caniuse.com/#feat=flexbox

**Comment by ludamad** [comment]
Resolved for now with flexbox

**Comment by ludamad** [comment]
Resolved for now with flexbox
